const translations = {
  pt: {
    "menu.title": "Casinha do Pão Menu",
    "section.drinks": "Bebidas",
    "section.toasts": "Tostas",
    "section.baguettes": "Baguetes",
    "section.sauces": "Molhos",
    "drink.water": "Água",
    "drink.water.desc": "Garrafa de 0.5L",
    "drink.juice": "Sumo Natural",
    "drink.juice.desc": "Laranja ou Manga",
    "drink.compal": "Compal",
    "drink.compal.desc": "Pêssego, Laranja, Maracujá ou Manga",
    "drink.tea": "Ice Tea",
    "drink.tea.desc": "Pêssego, Manga ou Limão",
    "drink.cola": "Coca-Cola",
    "drink.ucal": "Ucal",
    "drink.cafe": "Café",

    "toast.mista": "Tosta Mista",
    "toast.mista.desc": "Fiambre e Queijo ou Paio e Queijo",
    "toast.frango": "Tosta de Frango",
    "toast.frango.desc": "Frango, Tomate e Queijo",
    "toast.atum": "Tosta de Atum",
    "toast.atum.desc": "Atum, Tomate, Cebola e Oregãos",
    "toast.especial": "Tosta Especial da Casa",
    "toast.especial.desc": "Presunto, Queijo da Serra, Tomate e Molho Especial",
    "toast.simples": "Tosta Simples",
    "toast.simples.desc": "Fiambre ou Queijo",

    "baguette.frango": "Baguete de Frango",
    "baguette.frango.desc": "Pasta de Frango, Alface, Tomate e Ovo",
    "baguette.atum": "Baguete de Atum",
    "baguette.atum.desc": "Pasta de Atum, Alface, Tomate e Ovo",
    "baguette.delicias": "Baguete de Delícias do Mar",
    "baguette.delicias.desc": "Delícias do Mar, Alface, Maionese e Ovo",
    "baguette.serrana": "Baguete Serrana",
    "baguette.serrana.desc": "Presunto, Queijo e Molho Especial",
    "baguette.mista": "Baguete Mista",
    "baguette.mista.desc": "Fiambre, Queijo e Alface",

    "sauce.normal": "Molhos",
    "sauce.normal.desc": "Ketchup, Maionese ou Mostarda",
    "sauce.bbq": "Molho BBQ",
    "sauce.bbq.desc": "Fumado e ligeiramente doce",
    "sauce.alho": "Molho de Alho",
    "sauce.alho.desc": "Maionese com Alho",
  },
 en: {
    "menu.title": "Casinha do Pão Menu",
    "section.drinks": "Drinks",
    "section.toasts": "Toasts",
    "section.baguettes": "Baguettes",
    "section.sauces": "Sauces",
    "drink.water": "Water",
    "drink.water.desc": "0.5L Bottle",
    "drink.juice": "Natural Juice",
    "drink.juice.desc": "Orange or Mango",
    "drink.compal": "Compal",
    "drink.compal.desc": "Peach, Orange, Passion Fruit or Mango",
    "drink.tea": "Ice Tea",
    "drink.tea.desc": "Peach, Mango or Lemon",
    "drink.cola": "Coca-Cola",
    "drink.ucal": "Ucal",
    "drink.cafe": "Coffee",

    "toast.mista": "Ham and Cheese Toast",
    "toast.mista.desc": "Ham & Cheese or Cured Pork & Cheese",
    "toast.frango": "Chicken Toast",
    "toast.frango.desc": "Chicken, Tomato and Cheese",
    "toast.atum": "Tuna Toast",
    "toast.atum.desc": "Tuna, Tomato, Onion and Oregano",
    "toast.especial": "House Special Toast",
    "toast.especial.desc": "Cured Ham, Serra Cheese, Tomato & Special Sauce",
    "toast.simples": "Simple Toast",
    "toast.simples.desc": "Ham or Cheese",

    "baguette.frango": "Chicken Baguette",
    "baguette.frango.desc": "Chicken Spread, Lettuce, Tomato and Egg",
    "baguette.atum": "Tuna Baguette",
    "baguette.atum.desc": "Tuna Spread, Lettuce, Tomato and Egg",
    "baguette.delicias": "Seafood Baguette",
    "baguette.delicias.desc": "Seafood Sticks, Lettuce, Mayo and Egg",
    "baguette.serrana": "Serrana Baguette",
    "baguette.serrana.desc": "Cured Ham, Cheese & Special Sauce",
    "baguette.mista": "Ham & Cheese Baguette",
    "baguette.mista.desc": "Ham, Cheese & Lettuce",

    "sauce.normal": "Standard Sauces",
    "sauce.normal.desc": "Ketchup, Mayonnaise or Mustard",
    "sauce.bbq": "BBQ Sauce",
    "sauce.bbq.desc": "Smoky and slightly sweet",
    "sauce.alho": "Garlic Sauce",
    "sauce.alho.desc": "Garlic Mayo",
  },
  es: {
  "menu.title": "Casinha do Pão Menu",
  "section.drinks": "Bebidas",
  "section.toasts": "Tostadas",
  "section.baguettes": "Baguettes",
  "section.sauces": "Salsas",

  "drink.water": "Agua",
  "drink.water.desc": "Botella de 0.5L",
  "drink.juice": "Zumo Natural",
  "drink.juice.desc": "Naranja o Mango",
  "drink.compal": "Zumo Compal",
  "drink.compal.desc": "Melocotón, Naranja, Maracuyá o Mango",
  "drink.tea": "Té Helado",
  "drink.tea.desc": "Melocotón, Mango o Limón",
  "drink.cola": "Coca-Cola",
  "drink.ucal": "Ucal (Leche con Chocolate)",
  "drink.cafe": "Café",

  "toast.mista": "Tostada Mixta",
  "toast.mista.desc": "Jamón y Queso o Lomo y Queso",
  "toast.frango": "Tostada de Pollo",
  "toast.frango.desc": "Pollo, Tomate y Queso",
  "toast.atum": "Tostada de Atún",
  "toast.atum.desc": "Atún, Tomate, Cebolla y Orégano",
  "toast.especial": "Tostada Especial de la Casa",
  "toast.especial.desc": "Jamón Curado, Queso Serra, Tomate y Salsa Especial",
  "toast.simples": "Tostada Simple",
  "toast.simples.desc": "Jamón o Queso",

  "baguette.frango": "Baguette de Pollo",
  "baguette.frango.desc": "Pasta de Pollo, Lechuga, Tomate y Huevo",
  "baguette.atum": "Baguette de Atún",
  "baguette.atum.desc": "Pasta de Atún, Lechuga, Tomate y Huevo",
  "baguette.delicias": "Baguette de Surimi",
  "baguette.delicias.desc": "Surimi, Lechuga, Mayonesa y Huevo",
  "baguette.serrana": "Baguette Serrana",
  "baguette.serrana.desc": "Jamón Curado, Queso y Salsa Especial",
  "baguette.mista": "Baguette Mixta",
  "baguette.mista.desc": "Jamón, Queso y Lechuga",

  "sauce.normal": "Salsas Normales",
  "sauce.normal.desc": "Ketchup, Mayonesa o Mostaza",
  "sauce.bbq": "Salsa BBQ",
  "sauce.bbq.desc": "Ahumada y ligeramente dulce",
  "sauce.alho": "Salsa de Ajo",
  "sauce.alho.desc": "Mayonesa con Ajo"
},

  fr: {
  "menu.title": "Casinha do Pão Menu",
  "section.drinks": "Boissons",
  "section.toasts": "Tartines",
  "section.baguettes": "Baguettes",
  "section.sauces": "Sauces",

  "drink.water": "Eau",
  "drink.water.desc": "Bouteille de 0,5L",
  "drink.juice": "Jus Naturel",
  "drink.juice.desc": "Orange ou Mangue",
  "drink.compal": "Jus Compal",
  "drink.compal.desc": "Pêche, Orange, Fruit de la Passion ou Mangue",
  "drink.tea": "Thé Glacé",
  "drink.tea.desc": "Pêche, Mangue ou Citron",
  "drink.cola": "Coca-Cola",
  "drink.ucal": "Ucal (Lait au Chocolat)",
  "drink.cafe": "Café",

  "toast.mista": "Tartine Mixte",
  "toast.mista.desc": "Jambon et Fromage ou Saucisson et Fromage",
  "toast.frango": "Tartine au Poulet",
  "toast.frango.desc": "Poulet, Tomate et Fromage",
  "toast.atum": "Tartine au Thon",
  "toast.atum.desc": "Thon, Tomate, Oignon et Origan",
  "toast.especial": "Tartine Spéciale de la Maison",
  "toast.especial.desc": "Jambon Cru, Fromage Serra, Tomate et Sauce Spéciale",
  "toast.simples": "Tartine Simple",
  "toast.simples.desc": "Jambon ou Fromage",

  "baguette.frango": "Baguette au Poulet",
  "baguette.frango.desc": "Pâte de Poulet, Laitue, Tomate et Œuf",
  "baguette.atum": "Baguette au Thon",
  "baguette.atum.desc": "Pâte de Thon, Laitue, Tomate et Œuf",
  "baguette.delicias": "Baguette aux Bâtonnets de Crabe",
  "baguette.delicias.desc": "Bâtonnets de Crabe, Laitue, Mayonnaise et Œuf",
  "baguette.serrana": "Baguette Serrana",
  "baguette.serrana.desc": "Jambon Cru, Fromage et Sauce Spéciale",
  "baguette.mista": "Baguette Mixte",
  "baguette.mista.desc": "Jambon, Fromage et Laitue",

  "sauce.normal": "Sauces Classiques",
  "sauce.normal.desc": "Ketchup, Mayonnaise ou Moutarde",
  "sauce.bbq": "Sauce BBQ",
  "sauce.bbq.desc": "Fumée et légèrement sucrée",
  "sauce.alho": "Sauce à l'Ail",
  "sauce.alho.desc": "Mayonnaise à l'Ail"
},

de:{
  "menu.title": "Casinha do Pão Menu",
  "section.drinks": "Getränke",
  "section.toasts": "Toast",
  "section.baguettes": "Baguettes",
  "section.sauces": "Soßen",

  "drink.water": "Wasser",
  "drink.water.desc": "0,5L Flasche",
  "drink.juice": "Frischer Saft",
  "drink.juice.desc": "Orange oder Mango",
  "drink.compal": "Compal Saft",
  "drink.compal.desc": "Pfirsich, Orange, Maracuja oder Mango",
  "drink.tea": "Eistee",
  "drink.tea.desc": "Pfirsich, Mango oder Zitrone",
  "drink.cola": "Coca-Cola",
  "drink.ucal": "Ucal (Schokomilch)",
  "drink.cafe": "Kaffee",

  "toast.mista": "Schinken-Käse-Toast",
  "toast.mista.desc": "Schinken und Käse oder Wurst und Käse",
  "toast.frango": "Hähnchen-Toast",
  "toast.frango.desc": "Hähnchen, Tomate und Käse",
  "toast.atum": "Thunfisch-Toast",
  "toast.atum.desc": "Thunfisch, Tomate, Zwiebel und Oregano",
  "toast.especial": "Spezial-Toast des Hauses",
  "toast.especial.desc": "Rohschinken, Serra-Käse, Tomate und Spezialsoße",
  "toast.simples": "Einfacher Toast",
  "toast.simples.desc": "Schinken oder Käse",

  "baguette.frango": "Hähnchen-Baguette",
  "baguette.frango.desc": "Hähnchenpaste, Salat, Tomate und Ei",
  "baguette.atum": "Thunfisch-Baguette",
  "baguette.atum.desc": "Thunfischpaste, Salat, Tomate und Ei",
  "baguette.delicias": "Krabbenstäbchen-Baguette",
  "baguette.delicias.desc": "Krabbenstäbchen, Salat, Mayonnaise und Ei",
  "baguette.serrana": "Serrano-Baguette",
  "baguette.serrana.desc": "Rohschinken, Käse und Spezialsoße",
  "baguette.mista": "Gemischtes Baguette",
  "baguette.mista.desc": "Schinken, Käse und Salat",

  "sauce.normal": "Normale Soßen",
  "sauce.normal.desc": "Ketchup, Mayonnaise oder Senf",
  "sauce.bbq": "BBQ-Soße",
  "sauce.bbq.desc": "Rauchig und leicht süß",
  "sauce.alho": "Knoblauchsoße",
  "sauce.alho.desc": "Mayonnaise mit Knoblauch"
}


};

function setLanguage(lang) {
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    el.textContent = translations[lang][key] || key;
  });
}
